[default]
use_tests = true # XXX false
cache_lifetime = 300 # 5 minutes
use_cache = true
#use_cache = false

[debug]
use_tests = true

# Configure instead with
# export ROCKET_DATABASES='{diesel={url=postgres://user:pw@localhost/oauth}}'
[default.databases.diesel]
url = "postgres://user:pw@localhost/oauth"

[default.databases.redis]
url = "redis://127.0.0.1/"

